import manifest from "@/data/media.json";
import { MEDIA_BASE_URL } from "./site";

/**
 * Every photo and video on the site comes from src/data/media.json, which is
 * regenerated by `npm run media`. Nothing here needs editing by hand — drop
 * files into media-src/, run the command, commit the manifest.
 */

export type MediaCategory = "listing" | "vertical" | "landscape" | "agency";

export type MediaItem = {
  type: "image" | "video";
  category: MediaCategory;
  /** Either a bucket-relative key ("vertical/reel.mp4") or a site-absolute path. */
  src: string;
  /** Poster frame for videos, so the gallery renders before anything downloads. */
  poster?: string;
  width: number;
  height: number;
  alt?: string;
};

/** Site-absolute paths and full URLs pass through; bucket keys get the CDN prefix. */
export function mediaUrl(path: string): string {
  if (path.startsWith("/") || /^https?:\/\//.test(path)) return path;
  return `${MEDIA_BASE_URL}/${path}`;
}

/** Fallback shape when a manifest entry predates dimension probing. */
const DEFAULT_RATIO: Record<MediaCategory, number> = {
  listing: 4 / 5,
  vertical: 9 / 16,
  landscape: 16 / 9,
  agency: 9 / 16,
};

export function aspectRatio(item: MediaItem): number {
  if (item.width > 0 && item.height > 0) return item.width / item.height;
  return DEFAULT_RATIO[item.category];
}

export const MEDIA_ITEMS: MediaItem[] = manifest.items as MediaItem[];

export function mediaByCategory(category: MediaCategory): MediaItem[] {
  return MEDIA_ITEMS.filter((item) => item.category === category);
}
