import type { LightboxItem } from "@/components/VideoLightbox";
import manifest from "@/data/media.json";
import { MEDIA_BASE_URL } from "./site";

/**
 * Every photo and video on the site comes from src/data/media.json, which is
 * regenerated by `npm run media`. Nothing here needs editing by hand — drop
 * files into media-src/, run the command, commit the manifest.
 */

export type MediaCategory =
  | "listing" // property / listing photography
  | "vertical" // 9:16 listing reels
  | "landscape" // horizontal listing videos
  | "carousel" // carousel post artwork
  | "detail" // detail + vertical shots, used as stories
  | "testimonial" // client testimonial clips
  | "agency"; // brand and team

export type MediaItem = {
  type: "image" | "video";
  category: MediaCategory;
  /** Either a bucket-relative key ("vertical/reel.mp4") or a site-absolute path. */
  src: string;
  /** Poster frame for videos, so the gallery renders before anything downloads. */
  poster?: string;
  width: number;
  height: number;
  alt?: string;
};

/** Display order and copy for the gallery filters and the service examples. */
export const CATEGORY_LABELS: Record<MediaCategory, string> = {
  listing: "Listing Photography",
  vertical: "Vertical Video",
  landscape: "Listing Video",
  carousel: "Carousel Posts",
  detail: "Stories & Detail",
  testimonial: "Testimonials",
  agency: "Brand & Team",
};

export const CATEGORY_ORDER: MediaCategory[] = [
  "listing",
  "vertical",
  "landscape",
  "carousel",
  "detail",
  "testimonial",
  "agency",
];

/** Site-absolute paths and full URLs pass through; bucket keys get the CDN prefix. */
export function mediaUrl(path: string): string {
  if (path.startsWith("/") || /^https?:\/\//.test(path)) return path;
  return `${MEDIA_BASE_URL}/${path}`;
}

/** Fallback shape when a manifest entry predates dimension probing. */
const DEFAULT_RATIO: Record<MediaCategory, number> = {
  listing: 4 / 5,
  vertical: 9 / 16,
  landscape: 16 / 9,
  carousel: 1,
  detail: 9 / 16,
  testimonial: 9 / 16,
  agency: 9 / 16,
};

export function aspectRatio(item: MediaItem): number {
  if (item.width > 0 && item.height > 0) return item.width / item.height;
  return DEFAULT_RATIO[item.category];
}

export const isPortrait = (item: MediaItem) => aspectRatio(item) < 1;

export const MEDIA_ITEMS: MediaItem[] = manifest.items as MediaItem[];

export function mediaByCategory(...categories: MediaCategory[]): MediaItem[] {
  return MEDIA_ITEMS.filter((item) => categories.includes(item.category));
}

export function toLightboxItem(item: MediaItem): LightboxItem {
  if (item.type === "video") {
    return {
      type: "video",
      src: mediaUrl(item.src),
      poster: item.poster ? mediaUrl(item.poster) : undefined,
      aspect: isPortrait(item) ? "9/16" : "16/9",
    };
  }
  return { type: "image", src: mediaUrl(item.src), alt: item.alt };
}

/** Categories that actually have work in them — empty filters are never shown. */
export function populatedCategories(): MediaCategory[] {
  return CATEGORY_ORDER.filter((category) => MEDIA_ITEMS.some((item) => item.category === category));
}
