import type { LightboxItem } from "@/components/VideoLightbox";
import manifest from "@/data/media.json";
import { MEDIA_BASE_URL } from "./site";

/**
 * Every photo and video on the site comes from src/data/media.json, which is
 * regenerated by `npm run media`. Nothing here needs editing by hand — drop
 * files into media-src/, run the command, commit the manifest.
 */

export type MediaCategory =
  | "listing" // property / listing photography
  | "vertical" // 9:16 listing reels
  | "landscape" // horizontal listing videos
  | "carousel" // carousel post artwork — grouped into sets, shown in their own tab
  | "ad" // ad creative — variations and carousel ads, grouped into sets
  | "detail" // detail shots used as stories
  | "testimonial" // client testimonial story frames
  | "agency"; // brand and team

export type MediaItem = {
  type: "image" | "video";
  category: MediaCategory;
  /** Either a bucket-relative key ("vertical/reel.mp4") or a full URL / site path. */
  src: string;
  /** Poster frame for videos, so the gallery renders before anything downloads. */
  poster?: string;
  /** Files that belong to one post/ad share a set — shown as a single tile. */
  set?: string;
  width: number;
  height: number;
  alt?: string;
};

/** Site-absolute paths and full URLs pass through; bucket keys get the CDN prefix. */
export function mediaUrl(path: string): string {
  if (path.startsWith("/") || /^https?:\/\//.test(path)) return path;
  return `${MEDIA_BASE_URL}/${path}`;
}

/** Fallback shape when a manifest entry predates dimension probing. */
const DEFAULT_RATIO: Record<MediaCategory, number> = {
  listing: 4 / 5,
  vertical: 9 / 16,
  landscape: 16 / 9,
  carousel: 4 / 5,
  ad: 4 / 5,
  detail: 9 / 16,
  testimonial: 9 / 16,
  agency: 9 / 16,
};

export function aspectRatio(item: MediaItem): number {
  if (item.width > 0 && item.height > 0) return item.width / item.height;
  return DEFAULT_RATIO[item.category];
}

export const isPortrait = (item: MediaItem) => aspectRatio(item) < 1;

export const MEDIA_ITEMS: MediaItem[] = manifest.items as MediaItem[];

export function mediaByCategory(...categories: MediaCategory[]): MediaItem[] {
  return MEDIA_ITEMS.filter((item) => categories.includes(item.category));
}

export function toLightboxItem(item: MediaItem): LightboxItem {
  if (item.type === "video") {
    return {
      type: "video",
      src: mediaUrl(item.src),
      poster: item.poster ? mediaUrl(item.poster) : undefined,
      aspect: isPortrait(item) ? "9/16" : "16/9",
    };
  }
  return { type: "image", src: mediaUrl(item.src), alt: item.alt };
}

/* ── gallery tabs ──────────────────────────────────────────────────────────
 * A tab can pull from more than one manifest category — Stories is the
 * detail shots and the testimonial frames together. */

export type GalleryFilter = {
  id: "listing" | "vertical" | "landscape" | "carousel" | "ads" | "stories" | "agency";
  label: string;
  categories: MediaCategory[];
  /** Grouped tabs render one tile per set; clicking steps through the set. */
  grouped?: boolean;
};

export const GALLERY_FILTERS: GalleryFilter[] = [
  { id: "listing", label: "Listing Photography", categories: ["listing"] },
  { id: "vertical", label: "Vertical Video", categories: ["vertical"] },
  { id: "landscape", label: "Listing Video", categories: ["landscape"] },
  { id: "carousel", label: "Carousel Posts", categories: ["carousel"], grouped: true },
  { id: "ads", label: "Ads", categories: ["ad"], grouped: true },
  { id: "stories", label: "Stories", categories: ["detail", "testimonial"] },
  { id: "agency", label: "Brand & Team", categories: ["agency"] },
];

/** Tabs with no work in them are never shown. */
export function populatedFilters(): GalleryFilter[] {
  return GALLERY_FILTERS.filter((f) =>
    f.categories.some((c) => MEDIA_ITEMS.some((item) => item.category === c))
  );
}

/**
 * "All" is the property work — photography and video mixed into one montage.
 * Social artwork (carousels, stories) stays in its own tabs.
 */
const ALL_EXCLUDES: MediaCategory[] = ["carousel", "ad", "detail", "testimonial"];

export function allMontageItems(): MediaItem[] {
  const included = MEDIA_ITEMS.filter((item) => !ALL_EXCLUDES.includes(item.category));
  const photos = included.filter((item) => item.type === "image");
  const videos = included.filter((item) => item.type === "video");

  // Spread the videos evenly through the photos so the grid reads as one
  // montage instead of a block of videos followed by a block of photos.
  const keyed = [
    ...photos.map((item, i) => ({ item, k: (i + 0.5) / Math.max(photos.length, 1) })),
    ...videos.map((item, i) => ({ item, k: (i + 0.5) / Math.max(videos.length, 1) })),
  ];
  return keyed.sort((a, b) => a.k - b.k).map((e) => e.item);
}

/* ── sets ──────────────────────────────────────────────────────────────────
 * One tile per post/ad; clicking steps through its files in the lightbox.
 * Membership comes from the manifest's `set` field (written by npm run media
 * from subfolders or shared filename stems). Older entries without the field
 * fall back to the leading filename prefix. A file in no set is its own tile. */

export type MediaSet = { key: string; cover: MediaItem; items: MediaItem[] };

const naturalSort = (a: string, b: string) =>
  a.localeCompare(b, undefined, { numeric: true, sensitivity: "base" });

function fallbackSet(item: MediaItem): string {
  const name = item.src.split("/").pop() ?? item.src;
  return (name.match(/^[^0-9]+/)?.[0] ?? name).replace(/[-_.]+$/, "") || name;
}

export function mediaSets(...categories: MediaCategory[]): MediaSet[] {
  const groups = new Map<string, MediaItem[]>();
  for (const item of mediaByCategory(...categories)) {
    const key = item.set ?? fallbackSet(item);
    groups.set(key, [...(groups.get(key) ?? []), item]);
  }
  return [...groups.entries()]
    .sort(([a], [b]) => naturalSort(a, b))
    .map(([key, items]) => {
      const sorted = [...items].sort((a, b) => naturalSort(a.src, b.src));
      return { key, cover: sorted[0], items: sorted };
    });
}
